<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\WorkOrders.Api\WorkOrders.Api.csproj" />
    <ProjectReference Include="..\WorkOrders.Routing\WorkOrders.Routing.csproj" />
    <ProjectReference Include="..\WorkOrders.Notifications\WorkOrders.Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Nats" Version="13.5.3" />
    <PackageReference Include="Aspire.Hosting.PostgreSQL" Version="13.5.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>3df3a27d-eb6c-4948-bf46-4cae069689a1</UserSecretsId>
  </PropertyGroup>

</Project>
