<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\Directory\Directory.csproj" />
    <ProjectReference Include="..\Orders\Orders.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>929ffa4d-b661-4bb2-9919-30cc19db9978</UserSecretsId>
  </PropertyGroup>

</Project>
