<Project Sdk="Aspire.AppHost.Sdk/13.5.3">

  <ItemGroup>
    <ProjectReference Include="..\Orders\Orders.csproj" />
    <ProjectReference Include="..\Crew\Crew.csproj" />
    <ProjectReference Include="..\Notifications\Notifications.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Aspire.Hosting.Nats" Version="13.5.3" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AspireUseCliBundle>true</AspireUseCliBundle>
    <UserSecretsId>ba711645-e4be-4eac-8664-746a6d7aaa7d</UserSecretsId>
  </PropertyGroup>

</Project>
